name: CD Pipeline - Prod

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t newdeal-prod .
      - run: docker run -d --name intranet -p 80:80 newdeal-prod
      - run: sleep 2 && curl http://localhost:80